version: '3.8'

# TODO this is a work in progress docker-compose file, currently the DB is not used anywhere.
networks:
  development:
    driver: bridge

services:
  #########################
  ##     Persistence     ##
  #########################

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=api
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
    ports:
      - 5432:5432
    networks:
      - development
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 10s
      timeout: 5s
      retries: 5
    container_name: api-db
