name: cloudrun-deploy
on:
#  TODO in a real project, we would disallow pushing to master and always use pull requests instead
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: auth
        uses: 'google-github-actions/auth@v0'
        with:
          # Ideally we should pass these secrets from a secrets manager. Here we provide them from Github directly
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v0.6.0
        
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL  }}
          project_id: ${{ secrets.GCP_PROJECT_ID  }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app:latest

      - name: Deploy
        run: |
          gcloud run deploy nextjs-app \
          --region us-east1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/nextjs-app \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
